### ISSUE TITLE
always insert a new #> line when in comment mode

### ISSUE THREAD

**Issue by yhjhoo** [ant-druha/intellij-powershell#94] opened 2022-12-23 02:49 UTC
Original 

```
    <#
    .SYNOPSIS

    kcurrent
    display current kubernets namespaces

    
    #>
```
whenever I input a new line, it became following

<#
    .SYNOPSIS

    kcurrent
    display current kubernets namespaces

    
     #>
     #>
    #>

**Comment by ForNeVeR** [comment] 2023-10-01 20:14
Duplicate of #35. It is in my short list of issues I hope to start working on.

**Closed by ForNeVeR** 2023-10-01 20:14 UTC
